# Local domain supplied to Pi-hole v5 dnsmasq/FTL.
# location: /etc/dnsmasq.d/local.theama.co.conf
domain=local.theama.co

# Forward the local domain to Unbound
server=/local.theama.co/127.0.0.1#5335
server=/local.theama.co/::1#5335

# Forward IPv4 local PTR reverse lookups for 10.1.0.0/22
server=/0.1.10.in-addr.arpa/127.0.0.1#5335
server=/0.1.10.in-addr.arpa/::1#5335

server=/1.1.10.in-addr.arpa/127.0.0.1#5335
server=/1.1.10.in-addr.arpa/::1#5335

server=/2.1.10.in-addr.arpa/127.0.0.1#5335
server=/2.1.10.in-addr.arpa/::1#5335

server=/3.1.10.in-addr.arpa/127.0.0.1#5335
server=/3.1.10.in-addr.arpa/::1#5335

# Forward ULA /64 local PTR reverse lookups to Unbound
server=/1.0.0.0.1.7.9.6.8.a.a.5.6.3.d.f.ip6.arpa/127.0.0.1#5335
server=/1.0.0.0.1.7.9.6.8.a.a.5.6.3.d.f.ip6.arpa/::1#5335